-- 1. Create the 'venues' table
create table public.venues (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price text, -- stored as string for now e.g. "$50", can be integer later
  rating numeric,
  reviews integer,
  image text,
  address text,
  distance text,
  latitude float,
  longitude float,
  type text, -- 'Premium', 'Popular', etc.
  facilities jsonb -- stores array of facilities e.g. [{"icon": "Wifi", "label": "Free WiFi"}]
);

-- 2. Open up access to everyone (so the app can read it without logging in)
alter table public.venues enable row level security;

create policy "Enable read access for all users"
on public.venues
for select
using (true);

-- 3. Insert some dummy data so the app isn't empty
insert into public.venues (name, description, price, rating, reviews, image, address, distance, latitude, longitude, type, facilities)
values
(
  'Downtown Arena',
  'Premier 5-a-side facility with floodlights and changing rooms.',
  '$50',
  4.8,
  234,
  'https://as1.ftcdn.net/jpg/02/23/57/72/1000_F_223577247_DIyymsYzlK5U6Bu3T3ZJWauaVboyU2rY.jpg',
  '123 Football St, City Center',
  '1.2 km',
  40.7128,
  -74.0060,
  'Premium',
  '[{"label": "Free WiFi", "available": true}, {"label": "Parking", "available": true}]'
),
(
  'Westside Keepers',
  'Modern indoor facility with climate control.',
  '$45',
  4.5,
  187,
  'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?q=80&w=600&auto=format&fit=crop',
  '456 Sports Ave, West District',
  '2.1 km',
  40.7282,
  -73.9942,
  'Popular',
  '[{"label": "Showers", "available": true}, {"label": "Changing Rooms", "available": true}]'
);
